name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test01
      id: test01
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test01
        setup-command: ''
        command: conda init
        timeout: 10
    - name: conda init
      id: conda-init
      uses: education/autograding-command-grader@v1
      with:
        test-name: conda init
        setup-command: conda activate
        command: python Problem1/Test.py
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST01_RESULTS: "${{steps.test01.outputs.result}}"
        CONDA-INIT_RESULTS: "${{steps.conda-init.outputs.result}}"
      with:
        runners: test01,conda-init
